### ISSUE TITLE
fails to auto install on osx/arm

### ISSUE THREAD

**Issue by maxandersen** [quarkiverse/quarkus-ngrok#106]
on a laptop with no ngrok installed I get:

```
2024-01-24 09:12:40,717 INFO  [io.qua.ngr.dep.NgrokDevModeListener] (ngrok starter thread) Attempting to download ngrok from https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-darwin-arm64.zip
2024-01-24 09:12:40,722 INFO  [io.quarkus] (Quarkus Main Thread) code-with-quarkus stopped in 0.007s
Exit code: 47
Error: null
```

and then it exits.

A few issues in one:

1) even if something is wrong with the download we should not hard fail just because ngrok is failing to download
2) docs says ngrok.enabled=true has to be set before ngrok does something (I kinda disagree with that and prefer users to just be able to run with it by adding the extension and then make it possible to disable later)
3) then the core issue - why does it not work to download and what does exit code 47 mean.

**Comment by maxandersen** [comment]
current fix is to manually install ngrok btw.

**Comment by maxandersen** [comment]
ha - false alarm. didn't realize i was running this on a code-with-quarkus with only picocli in the mix. it thus just exited before it could finish downloading.

**Comment by melloware** [comment]
@all-contributors add @maxandersen for code
