### ISSUE TITLE
URIs generated by Quarkus REST (and probably other extensions) are not correct when tunning via ngrok

### ISSUE THREAD

**Issue by FroMage** [quarkiverse/quarkus-ngrok#125]
This is because Quarkus requires `quarkus.http.proxy.proxy-address-forwarding=true` to be set when running behind a reverse proxy (such as ngrok) in order to respect the proxy headers.

Without setting this, all URIs generated by the Quarkus application will be invalid, such as including an `http` scheme instead of `https` which is the only one opened by NGrok.

See https://quarkus.io/guides/http-reference#reverse-proxy

Also, I think the ngrok docs are a bit confusing at https://docs.quarkiverse.io/quarkus-ngrok/dev/#_usage because it claims it starts an `http` tunnel, but I've always seen ngrok to only open `https` tunnels. I don't know why you ended up with an http tunnel. Also, on the same paragraph, a link is improperly formatted.

**Comment by geoand** [comment]
Try #126 please

**Comment by melloware** [comment]
@geoand i will take care of releasing this new version it looks like @FroMage confirmed it works.

**Comment by geoand** [comment]
Thanks a lot!
