### ISSUE TITLE
DevUI: Add card that has external link to the proxied address

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-ngrok#130]
It would be cool if the Dev card has the external link that is posted in the log file.

**Comment by geoand** [comment]
Very good idea!

**Comment by melloware** [comment]
Looks like @phillip-kruger already did the hard work I am jsust doing a little refactoring.

![image](https://github.com/quarkiverse/quarkus-ngrok/assets/4399574/159e9c87-6061-4770-ac2b-1b6f77489c99)
