### ISSUE TITLE
Ngrok Release Build Failing

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-ngrok#132]
@gastaldi our Release is failing with

```
fatal: ambiguous argument 'docs/modules/ROOT/pages/includes/attributes.adoc': unknown revision or path not in the working tree.
```

But I don't understand why.

**Comment by gastaldi** [comment]
@melloware because the file does not exist?

**Comment by melloware** [comment]
HA yeah i didn't touch the docs but now let me look at making the docs standard.
