### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by zakhdar** [quarkiverse/quarkus-ngrok#142]
Just to declare a small typo in the documentation, in the "Usage" section there is a hyphen missing in the property name
"quarkus.ngrok.authtoken" -> "quarkus.ngrok.auth-token".
However, a message informs us that the application can't find the property, which puts us on the right track.

And above all, thank you for your contributions

**Comment by zakhdar** [comment]
Why not! 
I'll have a look at the contribution guide

**Comment by melloware** [comment]
Thanks for the fix!

**Comment by melloware** [comment]
@all-contributors add @zakhdar for docs
