### ISSUE TITLE
Investigate if a domain certificate policy can be revoked

### ISSUE THREAD

**Issue by sberyozkin** [quarkiverse/quarkus-ngrok#150]
We are looking with @cescoffier at an option of using NGrok for the Let's Encrypt ACME integration testing.
NGrok intercepts ACME challenge requests, and I've confirmed, with the help from the Ngrok service support, that after

```
ngrok api --api-key <YOUR-API-KEY> reserved-domains delete-certificate-management-policy <YOUR-RESERVED-DOMAIN-ID>
```

I can use NGrok to test the ACME flow.
`YOUR-RESERVED-DOMAIN-ID` is an id starting from `rd_` and is available in the NGrok dashboard's domain section.

If it were possible to get hold of `<YOUR-RESERVED-DOMAIN-ID>` then Quarkiverse Ngrok could be used to set up a devmode integration test for the Quarkus Let's Encrypt ACME feature.

**Comment by melloware** [comment]
This sounds doable!  Do you want me to look at adding this?

**Comment by sberyozkin** [comment]
@melloware It would be appreciated, please investigate, thanks

**Comment by melloware** [comment]
Sure thing let me look.

**Comment by melloware** [comment]
@sberyozkin @cescoffier a couple of questions.

1. Do you know your API_KEY and DOMAIN_ID?  meaning if I have optional configs and we detect the DOMAIN ID we can issue the revoke before starting ngrok?


```java
    /**
     * API key for ngrok if you need to perform any API operations such as delete-certificate-management-policy.
     */
    @ConfigItem
    public Optional<String> apiKey;

    /**
     * Reserved domain unique identifier for revoking certificate upon startup. Example: 'rd_2hrGw0rqFLOm9pcXf4dlbdNfrus'
     * If this value is not null the certificate will be revoked upon dev service startup.
     */
    @ConfigItem
    public Optional<String> reservedDomainId;
```

And if `reservedDomainId` is detected we would issue the revoke command before starting ngrok automatically?

**Comment by melloware** [comment]
@all-contributors add @sberyozkin for idea
