### ISSUE TITLE
Exiting from dev mode can leave ngrok still running

### ISSUE THREAD

**Issue by kdubb** [quarkiverse/quarkus-ngrok#87]
Sometimes exiting from dev mode will leave the ngrok process running.

I am not sure what the trigger is, it may be due to abnormal exits (e.g. CTRL+C) but it is intermittent. After this happens you _usually_ get an error when the next dev mode is started; but even then sometimes it manages to get more than one ngrok started and prints no message.

**Comment by geoand** [comment]
Weird... I can't say I know what to do about it :)

**Comment by melloware** [comment]
@kdubb can you try 1.3.0 please and let us know if you still get this issue?

**Comment by melloware** [comment]
@all-contributors add @kdubb for bug
