### ISSUE TITLE
Get same URL on every execution, is it possible?

### ISSUE THREAD

**Issue by raul-and** [quarkiverse/quarkus-ngrok#95]
Hello, I'm a student creating one of my first selfmade projects, I'm making a telegram bot using quarkus and ngrok. 
In order to process the messages I send to the bot via Telegram I have to use a class which has to extend TelegramWebhookBot, that class has some abstract methods which have to be overriden.
The method I'm having problems with is called "getBotPath", it basically returns the path of the bot a.k.a ngrok endpoint.
Everytime I execute the quarkus app a new endpoint is generated, I need it to be consistent, is there anyway possible you can help me with this problem?

Thanks.

**Comment by melloware** [comment]
I could be wrong but I think you have to pay NGrok for an account that gives you a dedicated URL. The free version automatically assigns you a different address every restart.

**Comment by geoand** [comment]
I'm no ngrok expert, but I think the same as @melloware

**Comment by gsmet** [comment]
If it’s for testing, you can also give smee.io a try. 

Also do you need the url to be stable or do you need it to be accessible so that you can return it?

**Comment by raul-and** [comment]
Yes it's for testing, I will have a look on smee.io thanks.
I think both ways work, if it's accessible and I can return it on getBotPath method it will work, also if its consistent I can put it on application.properties and reference it from there.

**Comment by gsmet** [comment]
@raul-and you will probably be interested by @maxandersen 's work here: https://github.com/quarkiverse/quarkus-ngrok/pull/98

**Comment by raul-and** [comment]
@gsmet @melloware Thanks! That's very useful.

**Comment by maxandersen** [comment]
Correct. Ngrok does allow *one* free static domain for its free plan. Just needs the domain to be set once #98 is in.
